# Generated by Django 5.2.16 on 2026-09-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0191_media_scored_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="read_time_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comic",
            name="read_time_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalbook",
            name="read_time_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalcomic",
            name="read_time_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalmanga",
            name="read_time_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="manga",
            name="read_time_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
